[package]
name = "boytacean"
description = "A Game Boy emulator that is written in Rust."
version = "0.1.1"
authors = ["João Magalhães <joamag@gmail.com>"]
license = "Apache-2.0"
keywords = ["gameboy", "emulator", "rust"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = ["wasm-bindgen"]

[dependencies]
wasm-bindgen = { version = "0.2", optional = true }

[profile.release]
debug = false
lto = true
opt-level = 3

[workspace]
members = [
    ".",
    "examples/sdl",
]
